### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by chicco785** [martel-innovate/deep-log-inspection#20]
* Requirements are not well documented.
   * Include in the installation manual a requirements section.
   * Detail the version of Docker used and the Hardware requirements to run both the server and the agent.
* HA deployment architecture of elk, is not presented (it should be detailed beside the high level one).
* Documentation ELK configuration is missing
   * What are the variables you can configure, what's their scope?
* Traefik is never mentioned in the documentation
   * Beside being cited in the architecture (where the role should be presented), it should be discussed its configuration (what's the meaning of the different variables? advisable configuration).
* `node.hostname == deeplogmanager` is never documented, but clearly is a required setting, how to apply that? isn't better a label? what if the hostname is not deeplogmanager in other configurations?
* changes to docker configuration are mentioned, but not indication on how to apply them is given: explain where to find this usually and how to reboot the daemon to apply the changes.

**Comment by chicco785** [comment]
not sure @taliaga want's to add more

**Comment by taliaga** [comment]
In *quickstart*:
- Add a pointer to the docker-compose file the quickstart is talking about. For a reader coming to the docs site that's not obvious. That should be mentioned even before the details of the docker limits config.
Regarding the limits, Mention where the docker config must be done (for someone new it's not clear if it should be in all nodes, only master, local cli).

  The quickstart should look like a short list of steps, which would consist of:

    - Prepare the docker swarm cluster where you will deploy the services (w/ links to https://docs.docker.com/get-started/part4/#create-a-cluster)
    - Clone this repo (git clone ....)
    - Review the configs (mention here volumes, limits, etc)
    - Docker stack deploy

In *Architecture*
- The diagram is a png, but if available, upload the "source" file of the diagram (not sure which tool was used to create it).

In UM Quickstart:
- Though well-rendered in github, the lists are broken in readthedocs. Maybe a different markdown flavour? check all your lists, not only in this section.

- Add link to https://www.elastic.co/guide/en/kibana/5.6/discover.html in "searching the logs", just like we have a link to visualizations in visualization part.

In *Configuring the Monasca Log API* (I&A Manual)
- Dockerfile & Enviroment Variables: Users don't need to edit API_PORT in the Dockerfile if you can do it in the compose, right? Same for the authentication variables. Instead of mentioning changes of env variables in the Dockerfile, add an environment section in the docker-compose file and instruct users to override those instead of having to rebuild the image (https://docs.docker.com/compose/compose-file/#environment).
